"""Remove redundant pipeline_version_id from the application_evaluations table

Revision ID: 91b3c3be3b43
Revises: 8630432205e8
Create Date: 2025-11-15 05:41:49.573026

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91b3c3be3b43"
down_revision: Union[str, Sequence[str], None] = "8630432205e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    old_enum = postgresql.ENUM(
        "APPROVED", "REJECTED", "NEEDS_REVIEW", name="loanapplicationresult"
    )
    new_enum = postgresql.ENUM(
        "APPROVED", "REJECTED", "NEEDS_REVIEW", name="evaluationresult"
    )

    # Create the new enum type in Postgres
    new_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "application_evaluations",
        "result",
        existing_type=old_enum,
        type_=new_enum,
        existing_nullable=True,
        postgresql_using="result::text::evaluationresult",
    )
    op.drop_constraint(
        op.f("application_evaluations_pipeline_version_id_fkey"),
        "application_evaluations",
        type_="foreignkey",
    )
    op.drop_column("application_evaluations", "pipeline_version_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()

    old_enum = postgresql.ENUM(
        "APPROVED", "REJECTED", "NEEDS_REVIEW", name="loanapplicationresult"
    )
    new_enum = postgresql.ENUM(
        "APPROVED", "REJECTED", "NEEDS_REVIEW", name="evaluationresult"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_evaluations",
        sa.Column(
            "pipeline_version_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        op.f("application_evaluations_pipeline_version_id_fkey"),
        "application_evaluations",
        "pipeline_versions",
        ["pipeline_version_id"],
        ["id"],
    )
    op.alter_column(
        "application_evaluations",
        "result",
        existing_type=new_enum,
        type_=old_enum,
        existing_nullable=True,
        postgresql_using="result::text::loanapplicationresult",
    )
    # ### end Alembic commands ###
