"""Add react flow nodes dict as a new pipeline version row

Revision ID: b10af5929dbe
Revises: 91b3c3be3b43
Create Date: 2025-11-16 09:42:15.439880

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b10af5929dbe"
down_revision: Union[str, Sequence[str], None] = "91b3c3be3b43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pipeline_versions", sa.Column("react_flow_nodes", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pipeline_versions", "react_flow_nodes")
    # ### end Alembic commands ###
